### ISSUE TITLE
Expand on README?

### ISSUE THREAD

**Issue by patcon** [lostisland/sawyer#11]
Ok firstly, the README is awesome. However, as someone arriving from octokit, trying to understand how this gem fits in, it's not very helpful in understand what this gem adds :)

Any chance you might think about expanding on it?

**Comment by pmackay** [comment]
+1. Would be useful to understand what hypermedia model it supports.

**Comment by Envek** [comment]
+1 on this too. Want give it a try, but too lazy to reverse engineer octokit.rb.

**Comment by declan** [comment]
+1

**Comment by spudowiar** [comment]
Sorry for the necrobump but it'd be nice to have a link to [SPEC.md](../tree/master/SPEC.md) since that's quite useful but not immediately the first thing you'd think of reading.
