### ISSUE TITLE
Update README to be useful

### ISSUE THREAD

**Issue by cemeyer2** [lostisland/sawyer#37]
Currently the README for this project is at best useless. Can one of the minatanters be responsible and update it so that it is actually useful for the community? I personally spent more time that I would like to admit trying to figure out why this gem was not doing what I expected it to do and realized the strange behavior by looking into the source code, a README of value would have avoided what I went though.

**Comment by The-Only79** [comment]
I am free man ✌

Thy Only 79-79 👆

The Godfather in my family  in my country.

**Comment by The-Only79** [comment]
Unsubscribe

**Comment by kkirsche** [comment]
I fully agree here. I have no clue what the actual use case for sawyer is and what it should do. I can dig into the source and really try to understand it, but I don't think that should be necessary in a library like this.

**Comment by chris-roerig** [comment]
I hate to be the "+1" guy but I agree with all the above.

**Comment by dancinglightning** [comment]
Had to read the source of this to actually understand how octokit uses this.

Some words about the main classes maybe, and what the "asses the situation" and "next action" would mean in ruby
