### ISSUE TITLE
Sawyer::Resource.as_json returns nested Arrays

### ISSUE THREAD

**Issue by artursapek** [lostisland/sawyer#39]
I don't grok why this library exists or why octokit felt the need to use it, but it gets a very fundamental thing wrong. `Sawyer::Resource.as_json` returns nested Arrays rather than a nested Hash. This makes it really hard to work with out of the box.

![image](https://cloud.githubusercontent.com/assets/897596/10341684/b56a2556-6ce3-11e5-9c59-ccd09d448212.png)

**Comment by pengwynn** [comment]
Sawyer doesn't know anything about `.as_json` since that's an ActiveModel method. I suspect `Sawyer::Resource#to_hash` will get you closer to your desired results.
