### ISSUE TITLE
Faraday dependency

### ISSUE THREAD

**Issue by ernsheong** [lostisland/sawyer#56]
`faraday` gem dependency is currently `['~> 0.8', '< 1.0']`

It should be `['>= 0.8', '< 1.0']` ? Currently version 0.9 of faraday is not allowed.

**Comment by technoweenie** [comment]
Thanks for the suggestion. I think I'll go with `['>= 0.8', '< 1.0']` based on [the team's plans](https://github.com/lostisland/faraday/issues/903).

I just filed #61. I'd appreciate a quick look if this is still relevant to you.

**Comment by ashmaroli** [comment]
@ernsheong Technically, `~> 0.8` will allow you to use `0.9` (in fact, any version between `0.8.0` and `1.0.0`)
You would be locked to `0.8.x` only if the constraint was `~> 0.8.0`.

*Just correcting a misconception.*

**Comment by technoweenie** [comment]
The Faraday dep is now `['>= 0.8', '< 2.0']` (ignore my original typo above) as of #61. There should be a new Sawyer release this week.
