### ISSUE TITLE
Relax dependency on addressable.

### ISSUE THREAD

**Issue by jpittis** [lostisland/sawyer#59]
Hey folks, I see sawyer has a hard dependency on addressable `< 2.6`. Is that for a good reason? Can we relax the dependency? Maybe `~> 2.3`?

**Comment by syoder** [comment]
I would like to know the answer to this as well.  I see a warning about "assigned but unused variable" when my project includes `Addressable` v2.5.2 - the only reason I can't update that gem is because `sawyer` depends on addressable `< 2.6`.

**Comment by theyork123** [comment]
#1116 Find a substitute for Sawyer in the gem or find a maintainer for it in 
Octokit/octokit.rb

**Comment by tarebyte** [comment]
@pengwynn @technoweenie is there a chance we could get this merged?

**Comment by technoweenie** [comment]
I think the intention was to prevent a new version of Addressable from breaking Sawyer. I don't think changing it to `~> 2.3` will work, as that'll lock you to `2.3.x`. I just merged #58, which will work with the current Addressable v2.6. Though now I'm thinking I should just leave it at `>= 2.3.5`.

**Comment by technoweenie** [comment]
The dependency has been relaxed to just `>= 2.3.5` in #61. I'll have a gem update out today. Thanks for the feedback and patience :)

**Comment by jpittis** [comment]
Thanks for making this happen @technoweenie. Lots of <3
